CREATE DATABASE IF NOT EXISTS olympics;
CREATE USER 'olympics' IDENTIFIED BY 'olympics';
GRANT ALL privileges ON `olympics`.* TO 'olympics'@'%';
FLUSH PRIVILEGES;
USE olympics;
CREATE TABLE IF NOT EXISTS player (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS country (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(60) NOT NULL,
    code VARCHAR(3) NOT NULL,
    `last` INT NOT NULL
);
CREATE TABLE IF NOT EXISTS event (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(60) NOT NULL,
    gender ENUM('Men''s', 'Women''s') NOT NULL,
    `date` INT NOT NULL
);
CREATE TABLE IF NOT EXISTS player_country (
    player_id INT NOT NULL,
    country_id INT NOT NULL,
    FOREIGN KEY(player_id) REFERENCES player(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(country_id) REFERENCES country(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS medal (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    country_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    FOREIGN KEY(country_id) REFERENCES country(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(event_id) REFERENCES event(id) ON UPDATE CASCADE ON DELETE CASCADE
);
INSERT INTO
    player (`name`)
VALUES
    ('Katie'),
    ('Tom');
INSERT INTO
    country (`name`, code, `last`)
VALUES
    -- Katie
    ('United States', 'USA', 46),
    ('Germany', 'GER', 17),
    ('Japan', 'JPN', 12),
    ('France', 'FRA', 10),
    ('South Korea', 'KOR', 9),
    ('Australia', 'AUS', 8),
    ('Netherlands', 'NED', 8),
    ('Hungary', 'HUN', 8),
    ('Spain', 'ESP', 7),
    ('Kenya', 'KEN', 6),
    ('Cuba', 'CUB', 5),
    ('New Zealand', 'NZL', 4),
    ('Argentina', 'ARG', 3),
    ('Denmark', 'DEN', 2),
    ('Sweden', 'SWE', 2),
    ('South Africa', 'RSA', 2),
    ('Serbia', 'SRB', 2),
    ('Portugal', 'POR', 0),
    ('Belgium', 'BEL', 2),
    ('Slovakia', 'SVK', 2),
    ('Belarus', 'BLR', 1),
    ('Slovenia', 'SLO', 1),
    ('Indonesia', 'INA', 1),
    ('Romania', 'ROU', 1),
    ('Bahrain', 'BRN', 1),
    ('Vietnam', 'VIE', 1),
    ('Ivory Coast', 'CIV', 1),
    ('Fiji', 'FIJ', 1),
    ('Puerto Rico', 'PUR', 1),
    ('Singapore', 'SIN', 1),
    ('Mexico', 'MEX', 0),
    ('Algeria', 'ALG', 0),
    ('Ireland', 'IRL', 0),
    ('Bulgaria', 'BUL', 0),
    ('Mongolia', 'MGL', 0),
    ('Niger', 'NIG', 0),
    ('Philippines', 'PHI', 0),
    ('Qatar', 'QAT', 0),
    ('Tunisia', 'TUN', 0),
    ('Israel', 'ISR', 0),
    ('Austria', 'AUT', 0),
    ('Nigeria', 'NGR', 0),
    ('United Arab Emirates', 'UAE', 0),
    -- Tom
    ('Great Britain', 'GBR', 27),
    ('China', 'CHN', 26),
    ('Russia', 'RUS', 19),
    ('Japan', 'JPN', 12),
    ('Italy', 'ITA', 8),
    ('Brazil', 'BRA', 7),
    ('Jamaica', 'JAM', 6),
    ('Czech Republic', 'CZE', 1),
    ('Croatia', 'CRO', 5),
    ('Canada', 'CAN', 4),
    ('Uzbekistan', 'UZB', 4),
    ('Colombia', 'COL', 3),
    ('Switzerland', 'SUI', 3),
    ('Kazakhstan', 'KAZ', 3),
    ('Iran', 'IRI', 3),
    ('Greece', 'GRE', 3),
    ('Ukraine', 'UKR', 2),
    ('Poland', 'POL', 2),
    ('North Korea', 'PRK', 2),
    ('Thailand', 'THA', 2),
    ('Georgia', 'GEO', 2),
    ('Azerbaijan', 'AZE', 1),
    ('Turkey', 'TUR', 1),
    ('Armenia', 'ARM', 1),
    ('Ethiopia', 'ETH', 1),
    ('Chinese Taipei', 'TPE', 1),
    ('Bahamas', 'BAH', 1),
    ('Independent Olympic Athletes', 'IOA', 1),
    ('Jordan', 'JOR', 1),
    ('Kosovo', 'KOS', 1),
    ('Tajikistan', 'TJK', 1),
    ('Malaysia', 'MAS', 0),
    ('Venezuela', 'VEN', 0),
    ('Lithuania', 'LTU', 0),
    ('India', 'IND', 0),
    ('Burundi', 'BDI', 0),
    ('Grenada', 'GRN', 0),
    ('Norway', 'NOR', 0),
    ('Egypt', 'EGY', 0),
    ('Dominican Republic', 'DOM', 0),
    ('Estonia', 'EST', 0),
    ('Finland', 'FIN', 0),
    ('Morocco', 'MAR', 0),
    ('Trinidad and Tobago', 'TTO', 0);
INSERT INTO
    player_country (player_id, country_id)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10),
    (1, 11),
    (1, 12),
    (1, 13),
    (1, 14),
    (1, 15),
    (1, 16),
    (1, 17),
    (1, 18),
    (1, 19),
    (1, 20),
    (1, 21),
    (1, 22),
    (1, 23),
    (1, 24),
    (1, 25),
    (1, 26),
    (1, 27),
    (1, 28),
    (1, 29),
    (1, 30),
    (1, 31),
    (1, 32),
    (1, 33),
    (1, 34),
    (1, 35),
    (1, 36),
    (1, 37),
    (1, 38),
    (1, 39),
    (1, 40),
    (1, 41),
    (1, 42),
    (1, 43),
    (2, 44),
    (2, 45),
    (2, 46),
    (2, 47),
    (2, 48),
    (2, 49),
    (2, 50),
    (2, 51),
    (2, 52),
    (2, 53),
    (2, 54),
    (2, 55),
    (2, 56),
    (2, 57),
    (2, 58),
    (2, 59),
    (2, 60),
    (2, 61),
    (2, 62),
    (2, 63),
    (2, 64),
    (2, 65),
    (2, 66),
    (2, 67),
    (2, 68),
    (2, 69),
    (2, 70),
    (2, 71),
    (2, 72),
    (2, 73),
    (2, 74),
    (2, 75),
    (2, 76),
    (2, 77),
    (2, 78),
    (2, 79),
    (2, 80),
    (2, 81),
    (2, 82),
    (2, 83),
    (2, 84);
